[package]
name = "rdrive"
version = "0.4.0"
edition.workspace = true
authors = ["周睿 <zrufo747@outlook.com>"]
repository.workspace = true
license = "MIT"
description = "A dyn driver manager."
keywords = ["os", "driver"]
categories = ["embedded", "no-std"]

[dependencies]
spin = "0.9"
fdt-parser = "0.4"
thiserror = { version = "2", default-features = false }
log = "0.4"
rdif-base = { version = "0.2", features = ["alloc"] }
rdif-intc = "0.3"
rdif-timer = "0.2"
rdif-power = "0.2"
