[package]
name = "rdrive"
version = "0.7.1"
edition.workspace = true
authors = ["周睿 <zrufo747@outlook.com>"]
repository.workspace = true
license = "MIT"
description = "A dyn driver manager."
keywords = ["os", "driver"]
categories = ["embedded", "no-std"]

[dependencies]
spin = "0.10"
fdt-parser = "0.4.15"
thiserror = { version = "2", default-features = false }
log = "0.4"

rdif-base = { workspace = true }
rdif-intc = { version = "0.7" }
rdif-timer = { version = "0.3" }
rdif-power = { version = "0.3" }
rdif-systick = { version = "0.2" }
rdif-block = { version = "0.1" }
rdif-clk = { version = "0.1" }
