[package]
authors = ["周睿 <zrufo747@outlook.com>"]
categories = ["embedded", "no-std"]
description = "Driver Interface base definition."
edition.workspace = true
keywords = ["os", "driver"]
license = "MIT"
name = "rdif-serial"
repository.workspace = true
version = "0.6.0"

[dependencies]
bitflags = "2.8"
futures = {version = "0.3", default-features = false, features = ["alloc"]}
rdif-base = {workspace = true}
spin = "0.10"
thiserror = {version = "2", default-features = false}
heapless = "0.9"